org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.warning.mode=all
org.gradle.java.installations.auto-download=false

systemProp.file.encoding=UTF-8

projectVersion=0.1.0-SNAPSHOT
org.gradle.java.installations.fromEnv=JAVA_HOME,JDK25,JDK21,JDK17,JDK8
