package dev.unifiedmc.geyser.pack;

import dev.unifiedmc.content.ContentCompileResult;
import dev.unifiedmc.content.ir.ContentIrDocument;
import dev.unifiedmc.content.ir.definitions.ContentBlockDefinition;
import dev.unifiedmc.content.ir.definitions.ContentItemDefinition;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.UUID;
import java.util.zip.Deflater;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/** Builds a deterministic Bedrock resource-pack archive from explicit IR texture identifiers. */
public final class BedrockResourcePackBuilder {
    public List<ContentCompileResult.EmittedArtifact> build(ContentIrDocument document) {
        String packId = "unifiedmc-" + document.modId() + "-bedrock";
        String headerUuid =
                UUID.nameUUIDFromBytes((packId + ":header").getBytes(StandardCharsets.UTF_8))
                        .toString();
        String moduleUuid =
                UUID.nameUUIDFromBytes((packId + ":module").getBytes(StandardCharsets.UTF_8))
                        .toString();

        List<Entry> entries = new ArrayList<>();
        entries.add(new Entry("manifest.json", manifestJson(packId, headerUuid, moduleUuid)));
        entries.add(new Entry("texts/languages.json", "[\"en_US\"]\n"));
        entries.add(
                new Entry("unifiedmc/asset-requirements.json", assetRequirementsJson(document)));

        byte[] zip = zip(entries);
        return List.of(
                new ContentCompileResult.EmittedArtifact(
                        Path.of("resourcepack/" + safeName(packId) + ".mcpack"), zip));
    }

    private static String manifestJson(String packId, String headerUuid, String moduleUuid) {
        return "{\n"
                + "  \"format_version\":2,\n"
                + "  \"header\":{\n"
                + "    \"name\":\""
                + esc(packId)
                + "\",\n"
                + "    \"description\":\"Generated by UnifiedMC; no Java resource-pack conversion performed\",\n"
                + "    \"uuid\":\""
                + headerUuid
                + "\",\n"
                + "    \"version\":[1,0,0]\n"
                + "  },\n"
                + "  \"modules\":[{\n"
                + "    \"type\":\"resources\",\n"
                + "    \"uuid\":\""
                + moduleUuid
                + "\",\n"
                + "    \"version\":[1,0,0]\n"
                + "  }]\n"
                + "}\n";
    }

    private static String assetRequirementsJson(ContentIrDocument document) {
        StringBuilder out =
                new StringBuilder(
                        "{\n  \"schema\":\"unifiedmc-bedrock-assets-1\",\n  \"assets\":[");
        List<String> assets = new ArrayList<>();
        for (ContentBlockDefinition block :
                document.blocks().stream()
                        .sorted(Comparator.comparing(b -> b.id().value()))
                        .toList()) {
            if (block.properties().containsKey("texture")) {
                assets.add(
                        assetJson(block.id().value(), "block", block.properties().get("texture")));
            }
        }
        for (ContentItemDefinition item :
                document.items().stream()
                        .sorted(Comparator.comparing(i -> i.id().value()))
                        .toList()) {
            if (item.properties().containsKey("texture")) {
                assets.add(assetJson(item.id().value(), "item", item.properties().get("texture")));
            }
        }
        for (int i = 0; i < assets.size(); i++) {
            if (i > 0) {

                out.append(',');
            }
            out.append("\n    ").append(assets.get(i));
        }
        out.append("\n  ]\n}\n");
        return out.toString();
    }

    private static String assetJson(String id, String kind, String source) {
        return "{\"id\":\""
                + esc(id)
                + "\",\"kind\":\""
                + kind
                + "\",\"source\":\""
                + esc(source)
                + "\",\"status\":\"MISSING_SOURCE_ASSET\"}";
    }

    private static byte[] zip(List<Entry> entries) {
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try (ZipOutputStream zip = new ZipOutputStream(baos, StandardCharsets.UTF_8)) {
                zip.setLevel(Deflater.BEST_COMPRESSION);
                entries.stream()
                        .sorted(Comparator.comparing(Entry::name))
                        .forEach(
                                entry -> {
                                    try {
                                        ZipEntry ze = new ZipEntry(entry.name());
                                        ze.setTime(0L);
                                        zip.putNextEntry(ze);
                                        zip.write(entry.content().getBytes(StandardCharsets.UTF_8));
                                        zip.closeEntry();
                                    } catch (IOException e) {
                                        throw new IllegalStateException(e);
                                    }
                                });
            }
            return baos.toByteArray();
        } catch (IOException e) {
            throw new IllegalStateException(
                    "Failed to build deterministic Bedrock resource pack", e);
        }
    }

    private static String safeName(String value) {
        return value.replace(':', '_').replace('/', '_').replace('\\', '_');
    }

    private static String esc(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private record Entry(String name, String content) {}
}
